# Generated by Django 5.2 on 2025-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={},
        ),
        migrations.RemoveField(
            model_name='drill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='description',
        ),
        migrations.AlterField(
            model_name='drill',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
