# Generated by Django 5.2 on 2025-10-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_drill_options_remove_drill_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={'ordering': ['title']},
        ),
    ]
