# Generated by Django 5.2 on 2025-11-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_enrollment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.drill'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('enrollment', 'drill')},
        ),
    ]
